# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-03 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20170603_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='loonatic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 3, 17, 22, 57, 943522, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loonatic',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 3, 17, 23, 4, 503190, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
