# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 21, 11, 41, 5, 851610, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 21, 11, 41, 21, 241276, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
